### ISSUE TITLE
Example of how to parse a document that contains multiple EDI document types

### ISSUE THREAD

**Issue by geovanimartinez** [EdiFabric/Sdk#1]
Hello,

Would you be able to add an example of how a document containing multiple EDI Document Types should be processed?. I need to parse documents that contain DELJITS, DELFOR, X12004010 all in the same file. I'm not able to figure out an optimal solution so any example would be great. Below is a screenshot of the contents of a file with two DELJIT and one DELFOR. 

![image](https://user-images.githubusercontent.com/222680/33105500-f5f4722a-cef2-11e7-92da-5a9b2840319c.png)

Right now I am splitting the document processing by index, 0-> 2 = 1st Edi Document
3 ->5 = 2nd Edi document and so on, but I know there has to be a better way that I maybe I have not uncovered or figured out.

Thank you for your time.

**Comment by EdiFabric** [comment]
You process the document exactly the same way as you would if it only contained one document type. I'm not really sure why would you split it . You have all the transactions and control segments already parsed (as seen in the screenshot), so you can pretty much do whatever you want with them at this stage. 
Example of what exactly would you like me to add ?

**Comment by geovanimartinez** [comment]
I dint explain my question well... below is what I am attempting to do, not sure if it may already be possible since its been a few months since I last worked with the SDK and noticed many changes made.

1. I read in, a text document that contains various EDI document types within; into a list 
2. each list item would representing an EDI document object contents 
3. within each EDI document object the contents would be listed (start UNB -> end UNZ)
4. I would then peek at the type of each list item and forward each item object to it's appropriate parsing function.

![image](https://user-images.githubusercontent.com/222680/40589335-3156e216-61b1-11e8-9bbc-26ec1b584ac9.png)

Then my code would look something like...

```
foreach(var ediDocument in EdiDocumentList[])
{
    if(ediDocument.DocumentType == EdiDocumentTypes.DELJIT)
        Process_DelJit_Document(ediDocument)

    if(ediDocument.DocumentType == EdiDocumentTypes.DELFOR)
        Process_Delfor_Document(ediDocument)
}
```
